#!/bin/bash
seed_ip=`getent hosts seed.mewhub.com | awk '{ print $1 }'`
source coinlist
source ~/komodo/src/pubkey.txt
args=("$@")
count=0
delay=15
while [ "x${coinlist[count]}" != "x" ]
do
  all=${coinlist[count]}
  name=${all%% *}
  supply=`expr "$all" : '.* \(.*\)'`
  if [ "$name" != "" ]
    then
     if [ $[RANDOM % 10] == 1 ]
      then
        gen=" -gen"
      else
        gen=""
      fi
     komodod -pubkey=$pubkey -ac_name=$name -ac_supply=$supply -addnode=$seed_ip $args &
     sleep $delay
    fi
  count=$(( $count +1 ))
done
