#!/bin/bash
source coinlist

sudo apt-get install ufw

sudo ufw disable
sudo ufw default deny incoming

sudo ufw allow 22    comment 'SSH'
sudo ufw allow 17775 comment 'Iguana Notary'
sudo ufw allow 7770  comment 'KMD'
sudo ufw allow 57777 comment 'CHIPS'
sudo ufw allow 40002 comment 'GAME'
#sudo ufw allow 8333  comment 'BTC'
sudo ufw allow 8888  comment 'HUSH'
sudo ufw allow 41878 comment 'EMC2'

for coins in "${coinlist[@]}"; do
    coin=($coins)

    if [[ ! ${ignoreacs[*]} =~ ${coin[0]} ]]; then
        acport=$(komodo-cli -ac_name=${coin[0]} getinfo | jq .p2pport)
        echo $acport
        sudo ufw allow $acport comment "${coin[0]}"
    fi
done

sudo ufw enable

# check the status again
sudo ufw status
