#!/bin/bash
sudo apt-get install ufw
sudo ufw disable
sudo ufw default deny incoming
sudo ufw allow 22      comment 'SSH port'
sudo ufw allow 7770  comment 'KMD port'
sudo ufw allow 7775  comment 'Iguana port'
sudo ufw allow 8333  comment 'BTC port'
sudo ufw allow 57777 comment 'CHIPS port'
sudo ufw allow 10195 comment 'REVS asset chain port'
sudo ufw allow 11340 comment 'SUPERNET asset chain port'
sudo ufw allow 11889 comment 'DEX asset chain port'
sudo ufw allow 14067 comment 'PANGEA asset chain port'
sudo ufw allow 15105 comment 'JUMBLR asset chain port'
sudo ufw allow 14249 comment 'BET asset chain port'
sudo ufw allow 8515  comment 'CRYPTO asset chain port'
sudo ufw allow 14430 comment 'HODL asset chain port'
#sudo ufw allow 10113 comment 'SHARK asset chain port'
sudo ufw allow 11963 comment 'BOTS asset chain port'
sudo ufw allow 12385 comment 'MGW asset chain port'
sudo ufw allow 8654  comment 'MVP asset chain port'
sudo ufw allow 12166 comment 'WLC asset chain port'
sudo ufw allow 8298  comment 'KV asset chain port'
sudo ufw allow 11115 comment 'CEAL asset chain port'
sudo ufw allow 9454 comment 'MESH asset chain port'
sudo ufw allow 14336 comment 'MNZ asset chain port'
sudo ufw allow 14275 comment 'COQUI'
sudo ufw allow 8845  comment 'MSHARK'
sudo ufw allow 12926 comment 'AXO'
sudo ufw allow 8799  comment 'BTCH'
sudo ufw allow 10270 comment 'ETOMIC'
sudo ufw allow 15487 comment 'VOTE2018'
sudo ufw allow 8426 comment 'NINJA'
sudo ufw allow 8922 comment 'BEER'
sudo ufw allow 11607 comment 'PIZZA'
sudo ufw enable
# check the status again
sudo ufw status
