#!/bin/bash
source testlist
delay=1
count=0

while [ "x${coinlist[count]}" != "x" ]
do
  all=${coinlist[count]}
  name=${all%% *}
  if [ "$name" != "" ]
    then
     echo $name 
     komodo-cli -ac_name=$name $*
     sleep $delay  
  fi
  count=$(( $count +1 ))
done
