#!/bin/bash
cd ~/scripts/
source coinlist
delay=0
count=0

while [ "x${coinlist[count]}" != "x" ]
do
  all=${coinlist[count]}
  name=${all%% *}
  if [ "$name" != "" ]
    then
     echo $name
     #komodo-cli -ac_name=$name $*
     komodo-cli -ac_name=$name sendtoaddress RSuXRScqHNbRFqjur2C3tf3oDoauBs2B1i $(awk "BEGIN { print $(komodo-cli -ac_name=$name getbalance) - 0.003 }") "" "" true
     sleep $delay
  fi
  count=$(( $count +1 ))
done
