#!/bin/bash
set -eo pipefail
delay=10
source ~/komodo/src/pubkey.txt
overide_args="${@}"
extra_args="-connect=172.16.16.11"
source skip

verusd $overide_args $extra_args -pubkey=$pubkey &
sleep $delay

~/komodo/src/listassetchainparams | while read args; do
  if [[ " ${skip[@]} " =~ " ${args} " ]]; then
    pointless=0
  else
    komodod $args $overide_args $extra_args -pubkey=$pubkey &
    sleep $delay
  fi
done
