#!/bin/bash
cd ~/scripts/
source coinlist
count=0
IFS=
now=$(date +"%Y-%m-%d %T%z")
btcinfo=$(bitcoin-cli getinfo)
kmdinfo=$(komodo-cli getinfo)
chipsinfo=$(chips-cli getinfo)
printf "$now \n";
format="%-10s %8s %8s %8s %12s\n"
printf "$format" "-ASSET-" "-NTRZd-" "-UTXOs-" "-BLOX-" "-BAL-";
printf "$format" "BTC" "$(bitcoin-cli listtransactions "" 77777 | grep -- -0.00098800 | wc -l)" "$(bitcoin-cli listunspent | grep .0001 | wc -l)" "$(echo $btcinfo | awk ' /\"blocks\"/ {printf $2}' | sed 's/,//')" "$(echo $btcinfo | awk ' /\"balance\"/ {printf $2}' | sed 's/,//')"
printf "$format" "KMD" "$(komodo-cli listtransactions "" 77777 | grep -- -0.00098800 | wc -l)" "$(komodo-cli listunspent | grep .0001 | wc -l)" "$(echo $kmdinfo | awk ' /\"blocks\"/ {printf $2}' | sed 's/,//')" "$(echo $kmdinfo | awk ' /\"balance\"/ {printf $2}' | sed 's/,//')"
printf "$format" "CHIPS" "$(chips-cli listtransactions "" 77777 | grep -- -0.00098000 | wc -l)" "$(chips-cli listunspent | grep .0001 | wc -l)" "$(echo $chipsinfo | awk ' /\"blocks\"/ {printf $2}' | sed 's/,//')" "$(echo $chipsinfo | awk ' /\"balance\"/ {printf $2}' | sed 's/,//')"

while [ "x${coinlist[count]}" != "x" ]
do
  all=${coinlist[count]}
  name=${all%% *}
  if [ "$name" != "" ]
    then
     info=$(komodo-cli -ac_name=$name getinfo)
     printf "$format" "$name" "$(komodo-cli -ac_name=$name listtransactions "" 77777 | grep -- -0.00098800 | wc -l)" "$(komodo-cli -ac_name=$name listunspent | grep .0001 | wc -l)" "$(echo $info | awk ' /\"blocks\"/ {printf $2}' | sed 's/,//')" "$(echo $info | awk ' /\"balance\"/ {printf $2}' | sed 's/,//')"
  fi
  count=$(( $count +1 ))
done
