#!/bin/bash
seed_ip=`getent hosts seed.mewhub.com | awk '{ print $1 }'`
source coinlist
count=0
delay=20

while [ "x${coinlist[count]}" != "x" ]
do
  all=${coinlist[count]}
  name=${all%% *}
  supply=`expr "$all" : '.* \(.*\)'`
  if [ "$name" != "" || "RFOX" ]
    then
     echo $name
     komodod -ac_name=$name -ac_supply=$supply -addnode=$seed_ip $1 &
     sleep $delay
    fi
  count=$(( $count +1 ))
done

#Other Coins
komodod -pubkey=$pubkey -ac_name=RFOX -ac_supply=1000000000 -ac_reward=100000000 -addnode=78.47.196.146 &

