#!/bin/bash
cd ~/scripts/
source coinlist
delay=1
count=0

while [ "x${coinlist[count]}" != "x" ]
do
  all=${coinlist[count]}
  name=${all%% *}
  if [ "$name" != "" ]
    then
     echo $name 
     komodo-cli -ac_name=$name $1 $2 $3 $4 $5 $6
     sleep $delay  
  fi
  count=$(( $count +1 ))
done
