#!/bin/bash
source coinlist
count=0

while [ "x${coinlist[count]}" != "x" ]
do
  all=${coinlist[count]}
  name=${all%% *}
  if [ "$name" != "" ]
    then
     echo $name
     processinfo=$(ps aux | grep komodod | grep $name)
     pid=$(echo $processinfo | awk '{print $2}')
     #gdb -p $pid &
echo $pid
  fi
  count=$(( $count +1 ))
done
