#!/bin/bash
source ~/komodo/src/pubkey.txt
echo "Starting Komodo"
komodod -gen -pubkey=$pubkey &
sleep 30
echo "Starting Chips"
chipsd -pubkey=$pubkey &
sleep 30
echo "Starting GameCredits"
gamecreditsd -pubkey=$pubkey &
#Starting Hush
#hushd -pubkey=$pubkey
